# Generated by Django 2.2 on 2019-04-19 15:56

import LottoWebCore.methods
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='MiddleMan',
            fields=[
                ('analysed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('id', models.CharField(default=LottoWebCore.methods.create_hash, max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('name', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('completed', models.BooleanField(default=False)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('lottery', models.DateTimeField(null=True, verbose_name='Sorteio')),
                ('id', models.CharField(default=LottoWebCore.methods.create_hash, max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Sorteio',
                'verbose_name_plural': 'Sorteios',
            },
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Solicitação de Registro',
                'verbose_name_plural': 'Solicitações de Registro',
            },
        ),
        migrations.CreateModel(
            name='StudentDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=500, verbose_name='Sala')),
                ('name', models.CharField(max_length=500, verbose_name='Nome')),
                ('phone', models.CharField(max_length=500, verbose_name='Telefone')),
                ('email', models.CharField(max_length=500, verbose_name='E-mail')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.City', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Centro Acadêmico',
                'verbose_name_plural': 'Centros Acadêmicos',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Universidade')),
                ('page', models.CharField(max_length=500, verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Universidade',
                'verbose_name_plural': 'Universidades',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('name', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('verified', models.BooleanField(default=False)),
                ('notified', models.BooleanField(default=False)),
                ('activated', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(default=LottoWebCore.methods.create_hash, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.StudentDirectory')),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.Raffle')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.MiddleMan')),
            ],
            options={
                'verbose_name': 'Bilhete',
                'verbose_name_plural': 'Bilhetes',
            },
        ),
        migrations.AddField(
            model_name='studentdirectory',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.University', verbose_name='Universidade'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.StudentDirectory'),
        ),
        migrations.AddField(
            model_name='middleman',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.StudentDirectory'),
        ),
        migrations.AddField(
            model_name='middleman',
            name='raffle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.Raffle'),
        ),
        migrations.AlterUniqueTogether(
            name='studentdirectory',
            unique_together={('name', 'city', 'university')},
        ),
        migrations.AlterUniqueTogether(
            name='middleman',
            unique_together={('name', 'directory', 'id', 'raffle')},
        ),
    ]
