# Generated by Django 2.2 on 2019-04-20 17:02

import LottoWebCore.methods
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='MiddleMan',
            fields=[
                ('name', models.CharField(max_length=500, null=True)),
                ('phone', models.CharField(max_length=500, null=True)),
                ('email', models.CharField(max_length=500, null=True)),
                ('analysed', models.BooleanField(default=False)),
                ('id', models.CharField(default=LottoWebCore.methods.create_hash, max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('name', models.CharField(max_length=500, verbose_name='Nome da Rifa')),
                ('phone', models.CharField(max_length=500, verbose_name='Telefone do Responsável')),
                ('email', models.CharField(max_length=500, verbose_name='E-mail')),
                ('completed', models.BooleanField(default=False, verbose_name='Finalizado')),
                ('creation', models.DateField(auto_now_add=True)),
                ('lottery', models.DateField(null=True, verbose_name='Data do Sorteio')),
                ('id', models.CharField(default=LottoWebCore.methods.create_hash, max_length=500, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Rifa',
                'verbose_name_plural': 'Rifas',
            },
        ),
        migrations.CreateModel(
            name='StudentDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nome do Centro')),
                ('phone', models.CharField(max_length=500, verbose_name='Telefone ou Ramal')),
                ('email', models.CharField(max_length=500, verbose_name='E-mail')),
                ('room', models.CharField(max_length=500, verbose_name='Sala')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.City', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Centro Acadêmico',
                'verbose_name_plural': 'Centros Acadêmicos',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Universidade')),
                ('page', models.CharField(max_length=500, verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Universidade',
                'verbose_name_plural': 'Universidades',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('name', models.CharField(max_length=500, null=True, verbose_name='Comprador')),
                ('phone', models.CharField(max_length=500, null=True, verbose_name='Telefone')),
                ('email', models.CharField(max_length=500, null=True, verbose_name='E-mail')),
                ('notified', models.BooleanField(default=False)),
                ('activated', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(default=LottoWebCore.methods.create_hash, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.StudentDirectory', verbose_name='Centro Acadêmico')),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.Raffle', verbose_name='Rifa')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.MiddleMan', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Bilhete',
                'verbose_name_plural': 'Bilhetes',
            },
        ),
        migrations.AddField(
            model_name='studentdirectory',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.University', verbose_name='Universidade'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.StudentDirectory', verbose_name='Centro Acadêmico'),
        ),
        migrations.AddField(
            model_name='middleman',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.StudentDirectory'),
        ),
        migrations.AddField(
            model_name='middleman',
            name='raffle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.Raffle'),
        ),
        migrations.AddField(
            model_name='middleman',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='profile'),
        ),
        migrations.AlterUniqueTogether(
            name='studentdirectory',
            unique_together={('name', 'university', 'city')},
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nome')),
                ('phone', models.CharField(max_length=500, verbose_name='Telefone')),
                ('email', models.CharField(max_length=500, unique=True, verbose_name='E-mail')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.StudentDirectory', verbose_name='Centro Acadêmico')),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.Raffle', verbose_name='Rifa')),
            ],
            options={
                'verbose_name': 'Solicitação de Registro',
                'verbose_name_plural': 'Solicitações de Registro',
                'unique_together': {('name', 'directory', 'raffle', 'email')},
            },
        ),
    ]
