# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('select_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=500, unique=True)),
                ('workload', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField(default=0)),
                ('term', models.CharField(max_length=500)),
                ('timetable', models.CharField(max_length=500)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WrkLD.Discipline')),
            ],
            options={
                'verbose_name_plural': 'Disciplinas',
                'verbose_name': 'Disciplina',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=500)),
                ('room', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('registry', models.IntegerField(default=0)),
                ('interest', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WrkLD.Department')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phd', models.IntegerField(default=0)),
                ('master', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=500)),
                ('page', models.CharField(max_length=500)),
                ('teachers', models.IntegerField(default=0)),
                ('employee', models.IntegerField(default=0)),
                ('foundation', models.IntegerField(default=0)),
                ('post_grads', models.IntegerField(default=0)),
                ('undergrads', models.IntegerField(default=0)),
                ('teachers_search', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WrkLD.Teacher'),
        ),
        migrations.AddField(
            model_name='department',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WrkLD.University'),
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together=set([('name', 'department')]),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set([('name', 'city', 'university')]),
        ),
    ]
