# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WrkLD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='code',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='discipline',
            unique_together=set([('name', 'code')]),
        ),
    ]
