# Generated by Django 2.2 on 2019-04-20 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middleman',
            name='directory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.StudentDirectory'),
        ),
    ]
