# Generated by Django 2.2 on 2019-04-19 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Finalizado'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.StudentDirectory', verbose_name='Centro Acadêmico'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='email',
            field=models.CharField(max_length=500, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='lottery',
            field=models.DateTimeField(null=True, verbose_name='Data do Sorteio'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Nome do Sorteio'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='phone',
            field=models.CharField(max_length=500, verbose_name='Telefone do Responsável'),
        ),
        migrations.AlterField(
            model_name='studentdirectory',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Nome do Centro'),
        ),
        migrations.AlterField(
            model_name='studentdirectory',
            name='phone',
            field=models.CharField(max_length=500, verbose_name='Telefone ou Ramal'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.CharField(max_length=500, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.CharField(max_length=500, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='raffle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.Raffle', verbose_name='Rifa'),
        ),
    ]
