# Generated by Django 2.2 on 2019-04-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0002_remove_ticket_directory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='raffle',
        ),
    ]
