# Generated by Django 2.2 on 2019-05-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0002_auto_20190428_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
