# Generated by Django 2.2 on 2019-04-19 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0002_auto_20190419_1843'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentdirectory',
            unique_together={('name', 'university')},
        ),
        migrations.RemoveField(
            model_name='studentdirectory',
            name='city',
        ),
    ]
