# Generated by Django 2.2 on 2019-04-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0002_auto_20190420_1353'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='middleman',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='middleman',
            name='directory',
        ),
    ]
