# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WrkLD', '0003_auto_20170707_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='analysed',
            field=models.BooleanField(default=False),
        ),
    ]
