# Generated by Django 2.2 on 2019-04-20 17:53

import LottoWebCore.methods
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0003_remove_ticket_raffle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.CharField(default=LottoWebCore.methods.create_hash, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
