# Generated by Django 2.2 on 2019-05-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0003_ticket_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Descrição da Premiação')),
            ],
        ),
        migrations.RemoveField(
            model_name='raffle',
            name='prizes',
        ),
        migrations.AddField(
            model_name='raffle',
            name='prizes',
            field=models.ManyToManyField(default=None, null=True, to='LottoWebCore.Prize'),
        ),
    ]
