# Generated by Django 2.2 on 2019-04-19 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0003_auto_20190419_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdirectory',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.City', verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='studentdirectory',
            unique_together={('name', 'university', 'city')},
        ),
    ]
