# Generated by Django 2.2 on 2019-04-20 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0003_auto_20190420_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='middleman',
            name='directory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.StudentDirectory'),
        ),
        migrations.AddField(
            model_name='middleman',
            name='raffle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.Raffle'),
        ),
        migrations.AlterUniqueTogether(
            name='middleman',
            unique_together={('id', 'directory', 'raffle')},
        ),
    ]
