# Generated by Django 2.2 on 2019-05-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0004_auto_20190505_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prize',
            options={'verbose_name': 'Prêmio', 'verbose_name_plural': 'Prêmios'},
        ),
        migrations.AddField(
            model_name='prize',
            name='qtde',
            field=models.IntegerField(default=1, max_length=100, verbose_name='Multiplicidade da Premiação'),
        ),
    ]
