# Generated by Django 2.2 on 2019-04-20 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0004_auto_20190420_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='directory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.StudentDirectory', verbose_name='Centro Acadêmico'),
            preserve_default=False,
        ),
    ]
