# Generated by Django 2.2 on 2019-04-20 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LottoWebCore', '0004_auto_20190419_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='middleman',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='middleman',
            name='directory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.StudentDirectory'),
        ),
        migrations.AlterField(
            model_name='middleman',
            name='email',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='middleman',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='middleman',
            name='phone',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Nome da Rifa'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.StudentDirectory', verbose_name='Centro Acadêmico'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Comprador'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.MiddleMan', verbose_name='Vendedor'),
        ),
    ]
