# Generated by Django 2.2 on 2019-04-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0005_auto_20190420_1334'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='middleman',
            unique_together={('directory', 'raffle')},
        ),
    ]
