# Generated by Django 2.2 on 2019-04-20 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0005_auto_20190419_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middleman',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='profile'),
        ),
    ]
