# Generated by Django 2.2 on 2019-05-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0005_auto_20190505_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='qtde',
            field=models.IntegerField(default=1, verbose_name='Multiplicidade da Premiação'),
        ),
    ]
