# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WrkLD', '0005_auto_20170709_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='analised',
            new_name='analysed',
        ),
    ]
