# Generated by Django 2.2 on 2019-04-20 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0006_auto_20190420_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='raffle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.Raffle', verbose_name='Rifa'),
            preserve_default=False,
        ),
    ]
