# Generated by Django 2.2 on 2019-04-20 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0006_auto_20190419_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='verified',
        ),
    ]
