# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WrkLD', '0006_auto_20170709_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='analysed',
        ),
    ]
