# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WrkLD', '0007_remove_teacher_analysed'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='analysed',
            field=models.BooleanField(default=True),
        ),
    ]
