# Generated by Django 2.2 on 2019-04-20 18:20

import LottoWebCore.methods
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0007_ticket_raffle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.CharField(default=LottoWebCore.methods.create_hash, max_length=500, primary_key=True, serialize=False, unique=True, verbose_name='Ticket ID'),
        ),
    ]
