# Generated by Django 2.2 on 2019-04-20 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0007_remove_ticket_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middleman',
            name='raffle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.Raffle'),
        ),
    ]
