# Generated by Django 2.2 on 2019-04-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0008_auto_20190420_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationrequest',
            name='description',
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='message',
            field=models.TextField(blank=True, verbose_name='Informações Adicionais'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='email',
            field=models.CharField(max_length=500, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Nome'),
        ),
    ]
