# Generated by Django 2.0.7 on 2018-07-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WrkLD', '0008_teacher_analysed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='analysed',
            field=models.BooleanField(default=False),
        ),
    ]
