# Generated by Django 2.2 on 2019-04-20 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0009_auto_20190420_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='directory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.StudentDirectory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='phone',
            field=models.CharField(default=1, max_length=500, verbose_name='Telefone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='raffle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.Raffle'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='registrationrequest',
            unique_together={('name', 'directory', 'raffle', 'email')},
        ),
        migrations.RemoveField(
            model_name='registrationrequest',
            name='message',
        ),
    ]
