# Generated by Django 2.0.7 on 2018-07-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WrkLD', '0009_auto_20180716_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='select_value',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
