# Generated by Django 2.2 on 2019-04-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0009_raffle_prizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='middleman',
            name='picture',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
