# Generated by Django 2.2 on 2019-04-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0010_middleman_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
