# Generated by Django 2.2 on 2019-04-20 15:18

import LottoWebCore.methods
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0010_auto_20190420_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raffle',
            options={'verbose_name': 'Rifa', 'verbose_name_plural': 'Rifas'},
        ),
        migrations.RemoveField(
            model_name='raffle',
            name='lottery',
        ),
        migrations.AlterField(
            model_name='raffle',
            name='id',
            field=models.CharField(default=LottoWebCore.methods.create_hash, max_length=500, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.StudentDirectory', verbose_name='Centro Acadêmico'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='raffle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LottoWebCore.Raffle', verbose_name='Rifa'),
        ),
    ]
