# Generated by Django 2.2 on 2019-04-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0011_ticket_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='social_media',
            field=models.CharField(max_length=500, null=True, verbose_name='Facebook/Instagram (URL)'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='username',
            field=models.CharField(max_length=12, null=True, verbose_name='Nome de Usuário'),
        ),
        migrations.AddField(
            model_name='studentdirectory',
            name='acronym',
            field=models.CharField(max_length=12, null=True, verbose_name='Sigla do Centro'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Nome Completo'),
        ),
    ]
