# Generated by Django 2.0.7 on 2018-07-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WrkLD', '0011_auto_20180716_1232'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'city', 'university')},
        ),
    ]
