# Generated by Django 2.0.7 on 2018-07-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WrkLD', '0012_auto_20180716_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='sigaa_home',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
