# Generated by Django 2.2 on 2019-04-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0013_auto_20190428_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='middleman',
            name='analysed',
        ),
        migrations.RemoveField(
            model_name='middleman',
            name='email',
        ),
        migrations.RemoveField(
            model_name='middleman',
            name='name',
        ),
    ]
