# Generated by Django 2.2 on 2019-04-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LottoWebCore', '0014_auto_20190428_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='analysed',
            field=models.BooleanField(default=False),
        ),
    ]
